# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    env:
      REPO_NAME: ${{ github.event.repository.name }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'



    - name: Set extension for Linux
      if: runner.os == 'Linux'
      run: echo "EXT=" >> $GITHUB_ENV

    - name: Set extension for Windows
      if: runner.os == 'Windows'
      run: echo "EXT=.exe" >> $env:GITHUB_ENV

    - name: Build
      run: go build -v -o build/${{ env.REPO_NAME }}${{ env.EXT }} ./...

    - name: Test
      run: go test -v ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.REPO_NAME }}-${{ matrix.os }}
        path: build/${{ env.REPO_NAME }}${{ env.EXT }}*
        if-no-files-found: error
